services:
  logstash:
    image: logstash:8.15.2
    container_name: logstash
    restart: always
    volumes:
      - ./docker/logstash/:/logstash_dir
      - ./docker/logstash/logs/:/logs
    command: logstash -f /logstash_dir/logstash.conf
    ports:
    - 9600:9600
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    restart: always
    volumes:
      - ./docker/elasticsearch:/usr/share/elasticsearch/data/
    environment:
      xpack.security.enabled: true
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: test
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - elk

  kibana:
    image: kibana:8.15.2
    container_name: kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_user
      - ELASTICSEARCH_PASSWORD=kibana_password
    depends_on:
      - elasticsearch  
    networks:
      - elk

networks:
  elk:
